#!/bin/bash

cd command_tests
./run_command_tests

cd ../harness_tests
./run_harness_tests

cd ../instruction_tests
./run_instruction_tests

cd ../zicsr_tests
./run_stage_2_tests

cd ../compiled_tests
./run_compiled_tests