#!/bin/zsh
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

test_cases=()

for file in expected/*; do
  if [[ -f "$file" ]]; then
    base="$(basename "$file" | rev | cut -d. -f2- | rev)"
    if [[ "$base" != *"-c" && "$base" != *"-v" ]]; then
      test_cases+=("$base")
    fi
  fi
done

for i in "${test_cases[@]}"; do

  OUT=$(diff -iw ${i}.log expected/${i}.log)
  ret=$?
  if [ "$OUT" != "" ]; then
    printf "\n${RED}${i}${NC}\n"
    echo "$OUT"
  elif [ $ret -eq 0 ]; then
    printf "\n${GREEN}${i}${NC}\n"
  else
    printf "${RED}Missing: ${i}${NC}\n"
  fi
  
done