#! /bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [ -f "$1.cmd" ]; then
  ../../rv64sim ${RV64SIM_FLAGS} < ${1}.cmd > ${1}${RV64SIM_FLAGS// /}.log

  OUT=$(diff -iw ${1}${RV64SIM_FLAGS// /}.log expected/${1}${RV64SIM_FLAGS// /}.log)
  ret=$?
  if [ "$OUT" != "" ]; then
    >&2 printf "\n${RED}${1}${NC}\n"
    echo "$OUT"
    exit 1
  elif [ $ret -eq 0 ]; then
    printf "\n${GREEN}${1}${NC}\n"
    exit 0
  else
    >&2 printf "${RED}Missing: ${1}${NC}\n"
    exit 2
  fi
else
  >&2 printf "${RED}Unknown test: ${1}${NC}\n"
  exit 3
fi